#!/usr/bin/env python3
"""Copy (unmodified) the OFL font chunks that cover the characters used by the UI.

Source: a directory of self-hosted Google Fonts chunks plus its
font-faces.generated.css (the AMADEUS repo's desktop/public/assets/fonts/s4-ds), read-only.
Chunks are copied byte-for-byte (no subsetting/renaming, so OFL Reserved Font
Name rules are not triggered). Writes src/assets/fonts/*.woff2 and src/fonts.css;
public/fonts/OFL.txt is maintained by hand for the families bundled here.
Run: AMADEUS_FONT_SRC=<chunk dir> python3 scripts/pick-fonts.py
"""
import glob, os, re, shutil, sys

SRC = os.environ.get('AMADEUS_FONT_SRC', '')
if not SRC or not os.path.isfile(os.path.join(SRC, 'font-faces.generated.css')):
    sys.exit('set AMADEUS_FONT_SRC to a directory containing font-faces.generated.css and the .woff2 chunks')
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'src/assets/fonts')

FAMILIES = {
    # css family in source -> (alias, weights wanted)
    'Noto Sans SC': ('AMD Sans', {'400', '500'}),
    'IBM Plex Mono': ('AMD Mono', {'400', '500'}),
}

css = open(os.path.join(SRC, 'font-faces.generated.css'), encoding='utf-8').read()
faces = re.findall(r'@font-face\s*{(.*?)}', css, re.S)

def parse_range(s):
    out = []
    for part in s.split(','):
        part = part.strip().replace('U+', '')
        if '-' in part:
            a, b = part.split('-')
            out.append((int(a, 16), int(b, 16)))
        elif part:
            v = int(part, 16)
            out.append((v, v))
    return out

text = ''
for f in [os.path.join(ROOT, 'index.html')] + glob.glob(os.path.join(ROOT, 'src/**/*.ts'), recursive=True):
    text += open(f, encoding='utf-8').read()
chars = {ord(c) for c in text} | set(range(0x20, 0x7f)) | {0x2026, 0x201c, 0x201d, 0x00b7, 0xff0c, 0x3001, 0x3002, 0xff1a}

os.makedirs(OUT, exist_ok=True)
picked = []
for body in faces:
    fam = re.search(r"font-family:\s*'([^']+)'", body).group(1)
    if fam not in FAMILIES:
        continue
    alias, weights = FAMILIES[fam]
    weight = re.search(r'font-weight:\s*(\d+)', body).group(1)
    if weight not in weights:
        continue
    url = re.search(r"url\('([^']+)'\)", body).group(1)
    rng = re.search(r'unicode-range:\s*([^;]+);', body).group(1)
    ranges = parse_range(rng)
    need = [c for c in chars if any(a <= c <= b for a, b in ranges)]
    if not need:
        continue
    fname = os.path.basename(url)
    shutil.copyfile(os.path.join(SRC, fname), os.path.join(OUT, fname))
    picked.append((alias, weight, fname, rng.strip(), len(need)))

lines = ['/* generated by scripts/pick-fonts.py — unmodified OFL chunks (Noto Sans SC, IBM Plex Mono); see public/fonts/OFL.txt */']
for alias, weight, fname, rng, n in picked:
    lines.append(
        "@font-face {\n  font-family: '%s';\n  font-style: normal;\n  font-weight: %s;\n  font-display: swap;\n"
        "  src: url('./assets/fonts/%s') format('woff2');\n  unicode-range: %s;\n}" % (alias, weight, fname, rng)
    )
open(os.path.join(ROOT, 'src/fonts.css'), 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
total = sum(os.path.getsize(os.path.join(OUT, p[2])) for p in picked)
for p in picked:
    print(p[0], p[1], p[2], 'covers', p[4], 'chars')
print('chunks', len(picked), 'bytes', total)
